---
# Create a virtual Python environment to contain python packages.
- name: Creating a virtual Python environment to install requirements
  command: "virtualenv {{ virtualenv_directory }}"
  when: virtualenv_directory is defined

# Change the path to the virtual environment if necessary.
- name: Changing the pip path to the virtual Python environment
  set_fact:
    pip: "{{ virtualenv_directory }}/bin/pip"
  when: virtualenv_directory is defined

# Install the Python packages using pip with the command module.
- name: Installing the Python packages
  # Using command module because the Ansible pip module may not be installed.
  command: "{{ pip }} install {{ item }}"
  with_items: "{{ packages['openstack'] }}"
  when: virtualenv_directory is defined

# Install the Python packages using pip with the command module.
- name: Installing the Python packages in the user directory
  # Using command module because the Ansible pip module may not be installed.
  command: "{{ pip }} install --user {{ item }}"
  with_items: "{{ packages['openstack'] }}"
  when: virtualenv_directory is not defined
