---
- name: A one time action to all the hosts in the inventory
  hosts: all
  vars:
    public_key: "{{ lookup('file', ansible_public_key_file) }}"
  tasks:
    # Add the public key to the authorized key file for ansible_user
    - name: Adding the public key to the authorized_key file
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ public_key }}"
