---
- name: Commands to clean up an OpenStack environment
  hosts: localhost
  vars:
    keypair_name: "{{ lookup('env', 'keypair_name') | default('keypair1', true) }}"
    network_name: "{{ lookup('env', 'network_name') | default('network1', true) }}"
    openstack_location: ""
    openstack_project: "{{ lookup('env', 'OS_PROJECT_NAME') }}"
    openstack_rc: "{{ lookup('env', 'openstack_rc_path') }}"
    public_network_name: "{{ lookup('env', 'public_network_name') }}"
    public_subnet_name: "{{ lookup('env', 'public_subnet_name') }}"
    router_name: "{{ lookup('env', 'router_name') }}"
    security_group_name: "{{ lookup('env', 'security_group_name') }}"
    server_name: "{{ lookup('env', 'server_name') }}"
    subnet_name: "{{ lookup('env', 'subnet_name') | default('subnet1', true) }}"
    subnet_range: "{{ lookup('env', 'subnet_range') | default('192.168.4.0/24', true) }}"

  vars_prompt:
    - name: "delete_flavors"
      prompt: "Delete the flavors? "
      default: no
      private: no
    - name: "delete_images"
      prompt: "Delete the images? "
      default: no
      private: no

  tasks:
    # Check the virtualenv for the openstack client
    - name: Checking the virtualenv for the openstack client
      stat:
        path: "virtualenv/bin/openstack"
      register: openstack_venv

    # When the file exists set the openstack location.
    - name: Setting the openstack client location to the virtualenv
      set_fact:
        openstack_location: "{{ openstack_venv.stat.path }}"
      when: openstack_venv.stat.exists and openstack_venv.stat.executable

    # The openstack variable source the rc file and contain the path to client.
    - name: Setting openstack variable to source the rc file and contain the path to the client
      set_fact:
        openstack: "source {{ openstack_rc }}; {{ openstack_location|default('openstack', true) }}"

    # Get the server ids that match the name.
    - name: Getting the server IDs that match the {{ server_name }}
      shell: "{{ openstack }} server list --name {{ server_name }} --format value -c ID"
      register: servers
      ignore_errors: true

    # Delete the servers.
    - name: Deleting the servers
      shell: "{{ openstack }} server delete {{ item }}"
      with_items: "{{ servers.stdout_lines }}"

    # Delete the keypair.
    - name: Deleting the keypair
      shell: "{{ openstack }} keypair delete {{ keypair_name }}"
      ignore_errors: true

    # Get the flavor ids.
    - name: Getting all the flavor ids
      shell: "{{ openstack }} flavor list --format value -c ID"
      register: flavors
      ignore_errors: true
      when: delete_flavors | bool == true

    # Delete the flavors.
    - name: Deleting all the flavors
      shell: "{{ openstack }} flavor delete {{ item }}"
      with_items: "{{ flavors.stdout_lines }}"
      # Some OpenStack environments do not let anyone delete flavors.
      ignore_errors: true
      when: delete_flavors | bool == true

    # Get the floating ips.
    - name: Getting all the floaing ip addresses
      shell: "{{ openstack }} floating ip list --format value -c ID"
      register: floating_ips

    # Delete the floating ips.
    - name: Deleting all the floating ip addresses
      shell: "{{ openstack }} floating ip delete {{ item }}"
      with_items: "{{ floating_ips.stdout_lines }}"

    # Delete the security group.
    - name: Deleting the security group {{ security_group_name }}
      shell: "{{ openstack }} security group delete {{ security_group_name }}"
      ignore_errors: true

    # Get the router ids.
    - name: Getting the routers named {{ router_name }}
      shell: "{{ openstack }} router list --name {{ router_name }} --format value -c ID"
      register: routers

    # Get the subnet ids.
    - name: Getting the subnets named {{ subnet_name }}
      shell: "{{ openstack }} subnet list --name {{ subnet_name }} --format value -c ID"
      register: subnets

    # Remove the subnet from the router.
    - name: Removing the subnet from the router
      shell: "{{ openstack }} router remove subnet {{ item.0 }} {{ item.1 }}"
      with_nested:
        - "{{ routers.stdout_lines }}"
        - "{{ subnets.stdout_lines }}"
      ignore_errors: true

    # Delete the subnet.
    - name: Deleting the subnet {{ subnet_name }}
      shell: "{{ openstack }} subnet delete {{ item }}"
      with_items: "{{ subnets.stdout_lines }}"

    # Get the network ids.
    - name: Getting the networks named {{ network_name }}
      shell: "{{ openstack }} network list --name {{ network_name }} --format value -c ID"
      register: networks

    # Delete the networks.
    - name: Deleting all the networks named {{ network_name }}
      shell: "{{ openstack }} network delete {{ item }}"
      with_items: "{{ networks.stdout_lines }}"

    # Get the router ids.
    - name: Getting the routers named {{ router_name }}
      shell: "{{ openstack }} router list --name {{ router_name }} --format value -c ID"
      register: routers

    # Delete the routers.
    - name: Deleting all the routers
      shell: "{{ openstack }} router delete {{ item }}"
      with_items: "{{ routers.stdout_lines }}"

    # Get the images.
    - name: Getting all the images
      shell: "{{ openstack }} image list --format value -c ID"
      register: images
      ignore_errors: true
      when: delete_images | bool == true

    # Delete the images.
    - name: Deleting all the images
      shell: "{{ openstack }} image delete {{ item }}"
      with_items: "{{ images.stdout_lines }}"
      ignore_errors: true
      when: delete_images | bool == true
