---
- name: The flavor genereator
  hosts: localhost
  vars:
    flavors:
      - name: container_storage
        vcpu: 16
        ram: 65536
        disk: 128
      - name: load_balancer
        vcpu: 4
        ram: 16384
        disk: 128
      - name: infra_elastic
        vcpu: 16
        ram: 65536
        disk: 128
      - name: m1.medium
        vcpu: 2
        ram: 4096
        disk: 40
      - name: master_etcd
        vcpu: 64
        ram: 245760
        disk: 512
      - name: node_small
        vcpu: 1
        ram: 2048
        disk: 32
      - name: node_average
        vcpu: 4
        ram: 16384
        disk: 64

    openstack_rc: "{{ lookup('env', 'openstack_rc_path') }}"
    openstack: source {{ openstack_rc }}; virtualenv/bin/openstack
  tasks:

    - name: Creating flavors
      shell: "{{ openstack }} flavor create --ram {{ item.ram }} --disk {{ item.disk }} --vcpus {{ item.vcpu }} --public {{ item.name }}"
      with_items: "{{ flavors }}"
