---
- name: The tasks to install Graphana in the OpenShift cluster
  hosts: masters
  tasks:

    - name: Printing Graphana information
      debug:
        msg: "Graphana would be installed and configured here."

    - name: Prepare mater | copy grafana files
      copy: src={{ item.src }} dest={{ item.dest }}
      mode: 755
      with_items:
        - { src: 'setup-grafana.sh', dest: '~/' }
        - { src: './templates/grafana-ocp.yaml', dest: '~/' }

    - name: Grafana | deploy grafana
      command: ~/setup-grafana.sh prometheus-ocp

    # TODO:// replace the shell with ansible commands
