---
- name: Install the requirements to run openshift-ansible-contrib installs
  hosts: target-host
  # Can not gather facts from hosts without Python installed.
  gather_facts: false
  vars:
    packages:
      common:
        - curl
        - gcc
        - git
        - libselinux-python
        - redhat-rpm-config
        - sshpass
      Fedora:
        - python2-devel
      CentOS:
        - epel-release
        - python-devel
        - python-pip
      RedHat:
        - python-devel
      python:
        - ansible==2.3.2
        - pip
        - dnspython
        - jinja2
        - jmespath
        - python-openstackclient==3.11.0
        - python-heatclient
        - shade

  tasks:
    # Ansible can not run if Python 2 is not already installed on the host.
    - name: Bootstrapping Python on this host
      become: true
      delegate_to: "{{ groups['openstack-server'][0] }}"
      raw: yum --assumeyes install python
      tags:
        - bootstrap
        - install

    # With Python (2) installed it should be safe to gather facts.
    - name: Gathering facts on the target host
      delegate_to: "{{ groups['openstack-server'][0] }}"
      setup:

    # Install the common operating system packages on the host.
    - name: Installing the common operating system software packages
      become: true
      delegate_to: "{{ groups['openstack-server'][0] }}"
      # Using raw, because the python yum package may not be installed.
      raw: yum --quiet --assumeyes install {{ item }}
      with_items: "{{ packages['common'] }}"
      tags:
        - os_common
        - install

    # Install operating system specific packages on the host.
    - name: Installing operating system specific software packages
      become: true
      delegate_to: "{{ groups['openstack-server'][0] }}"
      # Using raw, because the python yum package may not be installed.
      raw: yum --quiet --assumeyes install {{ item }}
      with_items: "{{ packages[ ansible_distribution ] }}"
      tags:
        - os_specific
        - install

    # Install the Python packages using pip.
    - name: Installing the Python packages using pip
      become: true
      delegate_to: "{{ groups['openstack-server'][0] }}"
      pip:
        name: "{{ item }}"
        state: latest
        extra_args: "--quiet"  # Pass the quit argument to reduce logging.
      with_items: "{{ packages['python'] }}"
      tags:
        - python
        - install
