---
- name: The general prerequisites to install OpenShift using Ansible.
  hosts: target-host
  # Can not gather facts from hosts without Python installed.
  gather_facts: false
  roles:
    - general-prerequisites
  tasks:
    # Print out the location of the ansible executable.
    - name: Printing out the path to ansible
      debug:
        msg: "{{ ansible_location }}"
      verbosity: 2

    # Print out the location of the ansible-playbook executable.
    - name: Printing out the path to ansible-playbook
      debug:
        msg: "{{ ansible_playbook_location }}"
      verbosity: 2
