---
- name: Install the requirements to run openshift-ansible-contrib installs
  hosts: target-host
  # Can not gather facts from hosts without Python installed.
  gather_facts: false
  vars:
    packages:
      common:
        - curl
        - gcc
        - git
        - libselinux-python
        - redhat-rpm-config
        - sshpass
      Fedora:
        - python2-devel
      CentOS:
        - python-devel
      RedHat:
        - python-devel
      python:
        - ansible
        - pip
        - dnspython
        - jinja2
        - jmespath
        - python-openstackclient==3.11.0
        - python-heatclient
        - shade

  tasks:
    # Ansible can not run if Python is not already installed on the host.
    - name: Bootstrap Python on this host
      become: true
      raw: yum --quiet --assumeyes install python
      tags:
        - bootstrap
        - install

    # With Python (2) installed it should be safe to gather facts.
    - name: Gather facts
      setup:

    # Install the common operating system packages on the host.
    - name: Install the common operating system software packages
      become: true
      # Using raw, because the python yum package may not be installed.
      raw: yum --quiet --assumeyes install {{ item }}
      with_items: "{{ packages['common'] }}"
      tags:
        - os_common
        - install

    # Install operating system specific packages on the host.
    - name: Install operating system specific software packages
      become: true
      # Using raw, because the python yum package may not be installed.
      raw: yum --quiet --assumeyes install {{ item }}
      with_items: "{{ packages[ ansible_distribution ] }}"
      tags:
        - os_specific
        - install

    # Install the Python packages using pip.
    - name: Install the Python packages
      become: true
      pip:
        name: "{{ item }}"
        state: latest
        extra_args: "--quiet"  # Pass the quit argument to reduce logging.
      with_items: "{{ packages['python'] }}"
      tags:
        - python
        - install
