---
- name: Configure openshift-ansible-contrib to run in this OpenStack environment
  hosts: target-host
  vars:
    # A list of regular expressions in all.yml and the replacement values.
    all_yml:
      - { find: "^env_id.*", replace: "env_id: \"{{ env_id }}\"" }
      - { find: "^public_dns_nameservers.*", replace: "public_dns_nameservers: [{{ public_dns_nameservers }}]" }
      - { find: "^openstack_ssh_public_key.*", replace: "openstack_ssh_public_key: \"{{ keypair_name }}\"" }
      - { find: "^openstack_external_network_name.*", replace: "openstack_external_network_name: \"{{ public_network_name }}\"" }
      - { find: "^openstack_default_image_name.*", replace: "openstack_defult_image_name: \"{{ default_image_name }}\"" }
      - { find: "^openstack_num_masters.*", replace: "openstack_num_masters: 3" }
      - { find: "^openstack_num_infra.*", replace: "openstack_num_infra: 3" }
      - { find: "^#openstack_master_flavor.*", replace: "openstack_master_flavor: \"master_etcd\"" }
      - { find: "^#openstack_infra_flavor.*", replace: "openstack_infra_flavor: \"load_balancer\"" }
      - { find: "^#openstack_node_flavor.*", replace: "openstack_node_flavor: \"node_small\"" }
      - { find: "^#openstack_lb_flavor.*", replace: "openstack_lb_flavor: \"load_balancer\"" }
      - { find: "^openstack_default_flavor.*", replace: "openstack_default_flavor: \"m1.medium\"" }
      - { find: "^#openstack_private_ssh_key.*", replace: "openstack_private_ssh_key: ~/.ssh/openstack"}
      # Do not use Cinder volumes. TODO: Remove this once Cinder is working.
      - { find: "^# ephemeral_volumes.*", replace: "ephemeral_volumes: true"}
    default_image_name: "{{ lookup('env', 'default_image_name') | default('ocp-3.7-rhel') }}"
    env_id: "{{ lookup('env', 'env_id') | default('scale-ci', true) }}"
    keypair_name: "{{ lookup('env', 'keypair_name') | default('ci_keypair', true) }}"
    # The openshift-ansible repository to use if the code is not already on the host.
    openshift_ansible_repo: "{{ lookup('env', 'openshift_ansible_repo') | default('https://github.com/openshift/openshift-ansible', true) }}"
    # The version can be a branch, tag, or hash for testing pull requests.
    openshift_ansible_version: "{{ lookup('env', 'openshift_ansible_version') | default('HEAD', true) }}"
    # The openshift-ansible-contrib repository to use (required).
    openshift_ansible_contrib_repo: "{{ lookup('env', 'openshift_ansible_contrib_repo') | default('https://github.com/openshift/openshift-ansible-contrib', true) }}"
    # This version can be a branch, tag, or hash for testing pull requests.
    openshift_ansible_contrib_version: "{{ lookup('env', 'openshift_ansible_contrib_version') | default('HEAD', true) }}"
    openstack_rc: "{{ lookup('env', 'openstack_rc_path') | default('keystonerc', true) }}"
    public_network_name: "{{ lookup('env', 'public_network_name') | default('public_network', true) }}"
    public_subnet_name: "{{ lookup('env', 'public_subnet_name') | default('public_subnet', true) }}"

  tasks:
    # Remove all old directories and files.
    - name: Removing any old directories or files from previous attempts
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "keystonerc"
        - "openshift-ansible"
        - "openshift-ansible-contrib"
        - "inventory"
        - "ansible.cfg"

    # Check if the server contains the openshift-ansible code already.
    - name: Checking file system status for the openshift-ansible directory
      stat:
        get_checksum: no
        get_md5: no
        path: "/root/openshift-ansible"
      become: true
      register: openshift_ansible

    # Create a symbolic link to the openshift-ansible directory.
    - name: Creating a symbolic link to the openshift-ansible directory
      file:
        src: /root/openshift-ansible
        path: "{{ ansible_user_dir }}/openshift-ansible"
        state: link
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true
      when: openshift_ansible['stat']['exists']

    # Print the values that will be used for the openshift-ansible repository.
    - name: Printing the values used to clone openshift-ansible
      debug:
        msg: "openshift-ansible repository: {{ openshift_ansible_repo }} {{ openshift_ansible_version }}"
      when: openshift_ansible['stat']['exists'] == false

    # Get a fresh clone of the openshift-ansible GitHub project.
    - name: Cloning the openshift-ansible repository
      git:
        dest: "{{ ansible_user_dir }}/openshift-ansible"
        # Specify a different repo to test someone else's repository.
        repo: "{{ openshift_ansible_repo }}"
        # Specify a version for a different branch, tag, or hash to verify PRs.
        version: "{{ openshift_ansible_version }}"
      when: openshift_ansible['stat']['exists'] == false

    # Print the values that will be used for openshift-ansible-contrib.
    - name: Printing the values used to clone openshift-ansible-contrib
      debug:
        msg: "openshift-ansible-contrib repository: {{ openshift_ansible_contrib_repo }} {{ openshift_ansible_contrib_version }}"

    # Get a fresh clone of the openshift-ansible-contrib GitHub project.
    - name: Cloning the openshift-ansible-contrib repository
      git:
        dest: "{{ ansible_user_dir }}/openshift-ansible-contrib"
        # Specify a different repo to test someone else's repository.
        repo: "{{ openshift_ansible_contrib_repo }}"
        # Specify a version for a different branch, tag, or hash to verify PRs.
        version: "{{ openshift_ansible_contrib_version }}"

    # Set the contrib playbooks provisioning openstack path.
    - name: Creating the openshift_openstack directory variable
      set_fact:
        openshift_openstack_dir: "openshift-ansible-contrib/playbooks/provisioning/openstack"

    # Install the ansible-galaxy requirements.
    - name: Running the ansible-galaxy install command
      command: "ansible-galaxy install -r {{ openshift_openstack_dir }}/galaxy-requirements.yaml -p openshift-ansible-contrib/roles"

    # Copy the remote sample-inventory to another remote directory.
    - name: Copying the sample inventory directory
      # Note: The copy module does not support recurisve copy of remote sources.
      command: cp -r {{ openshift_openstack_dir }}/sample-inventory/ inventory

    # Copy the Ansible configuration file from the inventory directory.
    - name: Copying the Ansible configuration file from inventory
      copy:
        remote_src: true
        src: inventory/ansible.cfg
        dest: ./ansible.cfg

    # Remove the ansible.cfg file.
    - name: Removing the Ansible configuration file
      file:
        path: inventory/ansible.cfg
        state: absent

    # Create a .ssh directory if one does not already exist.
    - name: Creating the .ssh directory
      file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: 0700

    # Copy the private key so this server can access the OpenShift servers.
    - name: Copying the private key to the system
      copy:
        src: "{{ ansible_private_key_file }}"
        dest: "{{ ansible_user_dir }}/.ssh/openshift"
        mode: 0600

    # Copy the public key so this server.
    - name: Copying the public key to the system
      copy:
        src: "{{ ansible_public_key_file }}"
        dest: "{{ ansible_user_dir }}/.ssh/openshift.pub"
        mode: 0644

    # Copy the OpenStack rc file from the Ansible host to the target host.
    - name: Copying the OpenStack rc file to {{ openstack_rc }}
      copy:
        src: "keystonerc"
        dest: "{{ openstack_rc }}"

    # Add an authentication block to the end of the OSEv3 file.
    - name: Adding authentication information to the end of the OSEv3.yml file
      blockinfile:
        backup: yes
        block: "{{ lookup('file', 'templates/auth_block.yml') }}"
        insertafter: EOF
        path: inventory/group_vars/OSEv3.yml

    # For each item in the list, search for regular expressions and replace.
    - name: Changing the desired lines in inventory/group_vars/all.yml
      lineinfile:
        path: inventory/group_vars/all.yml
        regexp: "{{ item['find'] }}"
        line: "{{ item['replace'] }}"
      with_items: "{{ all_yml }}"

    # Set a variable for the ansible-playbook.
    - name: Setting ansible-playbook variable
      set_fact:
        ansible_playbook: "source {{ openstack_rc }}; ansible-playbook"

    # Run the Ansible playbook that installs OpenStack.
    - name: Running the OpenStack install
      shell: "{{ ansible_playbook }} -vv {{ openshift_openstack_dir }}/provision.yaml 2>&1 > openstack_provision_log.txt"
      args:
        # Use bash to get the posix style redirects.
        executable: /bin/bash

    # Run the Ansible playbook that installs OpenShift.
    - name: Running the OpenShift install
      shell: "{{ ansible_playbook }} -vv openshift-ansible/playbooks/byo/config.yml 2>&1 > openshift_install_log.txt"
      args:
        # Use bash to get the posix style redirects.
        executable: /bin/bash

    # Print out the log file locations.
    - name: Printing out the log file locations
      debug:
        msg: "Installation complete, check the openstack_provision_log.txt and openshift_install_log.txt for errors."
