---
- name: Copy the overcloudrc file from the openstack-server
  hosts: openstack-server
  tasks:
    # Copy the OpenStack rc file from the OpenStack server.
    - name: Fetching the OpenStack rc file from the openstack-server
      fetch:
        src: "{{ openstack_rc }}"
        flat: yes
        dest: "{{ playbook_dir }}/openstackrc"

# import_playbook to start the openstack setup.
- include: setup_openstack_environment.yml
