---
- name: Prepare a remote openstack-server to run scale-ci
  hosts: openstack-server
  vars:
    install_directory: "{{ ansible_user_dir }}/scale-ci"
    virtualenv_directory: "{{ install_directory }}/virtualenv"
  pre_tasks:
    # Delete any existing code before the role installs the prerequisites.
    - name: Deleting any existing code on the openstack-server
      file:
        path: "{{ install_directory }}"
        state: absent
  roles:
    - general-prerequisites

# import_playbook to start the openstack setup.
- include: setup_openstack_environment.yml
