---
- name: Prepare a remote openstack-server to run scale-ci
  hosts: openstack-server
  vars:
    install_directory: "{{ ansible_user_dir }}/scale-ci"
    virtualenv_directory: "{{ install_directory }}/virtualenv"
  pre_tasks:
    # Delete any existing code before the role installs the prerequisites.
    - name: Deleting any existing code on the openstack-server
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ install_directory }}"
        - "{{ ansible_user_dir }}/.ssh/known_hosts"
  roles:
    - general-prerequisites
  tasks:
    # Copy the public key so it can be used to create the OpenStack keypair.
    - name: Copying the public key to openstack-server
      copy:
        src: "{{ ansible_public_key_file }}"
        dest: "{{ install_directory }}/key.public"

    # Copy the private key so it can be used to access OpenStack VMs.
    - name: Copying the private key to openstack-server
      copy:
        src: "{{ ansible_private_key_file }}"
        dest: "{{ install_directory }}/key.private"
        mode: 0600

# import_playbook to start the openstack setup.
- include: setup_openstack_environment.yml
